// Code generated by protoc-gen-go. DO NOT EDIT.
// source: scrape.proto

package proto

import proto1 "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto1.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// The request message containing the user's name.
type ScrapeRequest struct {
	Url    string `protobuf:"bytes,1,opt,name=url" json:"url,omitempty"`
	Filter string `protobuf:"bytes,2,opt,name=filter" json:"filter,omitempty"`
}

func (m *ScrapeRequest) Reset()                    { *m = ScrapeRequest{} }
func (m *ScrapeRequest) String() string            { return proto1.CompactTextString(m) }
func (*ScrapeRequest) ProtoMessage()               {}
func (*ScrapeRequest) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{0} }

func (m *ScrapeRequest) GetUrl() string {
	if m != nil {
		return m.Url
	}
	return ""
}

func (m *ScrapeRequest) GetFilter() string {
	if m != nil {
		return m.Filter
	}
	return ""
}

// The response message containing the greetings
type ScrapeReply struct {
	Message bool `protobuf:"varint,1,opt,name=message" json:"message,omitempty"`
}

func (m *ScrapeReply) Reset()                    { *m = ScrapeReply{} }
func (m *ScrapeReply) String() string            { return proto1.CompactTextString(m) }
func (*ScrapeReply) ProtoMessage()               {}
func (*ScrapeReply) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{1} }

func (m *ScrapeReply) GetMessage() bool {
	if m != nil {
		return m.Message
	}
	return false
}

func init() {
	proto1.RegisterType((*ScrapeRequest)(nil), "proto.ScrapeRequest")
	proto1.RegisterType((*ScrapeReply)(nil), "proto.ScrapeReply")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for Scraper service

type ScraperClient interface {
	// Sends a greeting
	Scrape(ctx context.Context, in *ScrapeRequest, opts ...grpc.CallOption) (*ScrapeReply, error)
}

type scraperClient struct {
	cc *grpc.ClientConn
}

func NewScraperClient(cc *grpc.ClientConn) ScraperClient {
	return &scraperClient{cc}
}

func (c *scraperClient) Scrape(ctx context.Context, in *ScrapeRequest, opts ...grpc.CallOption) (*ScrapeReply, error) {
	out := new(ScrapeReply)
	err := grpc.Invoke(ctx, "/proto.Scraper/Scrape", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Scraper service

type ScraperServer interface {
	// Sends a greeting
	Scrape(context.Context, *ScrapeRequest) (*ScrapeReply, error)
}

func RegisterScraperServer(s *grpc.Server, srv ScraperServer) {
	s.RegisterService(&_Scraper_serviceDesc, srv)
}

func _Scraper_Scrape_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ScrapeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ScraperServer).Scrape(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.Scraper/Scrape",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ScraperServer).Scrape(ctx, req.(*ScrapeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Scraper_serviceDesc = grpc.ServiceDesc{
	ServiceName: "proto.Scraper",
	HandlerType: (*ScraperServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Scrape",
			Handler:    _Scraper_Scrape_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "scrape.proto",
}

func init() { proto1.RegisterFile("scrape.proto", fileDescriptor1) }

var fileDescriptor1 = []byte{
	// 178 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x29, 0x4e, 0x2e, 0x4a,
	0x2c, 0x48, 0xd5, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x05, 0x53, 0x4a, 0x96, 0x5c, 0xbc,
	0xc1, 0x60, 0xe1, 0xa0, 0xd4, 0xc2, 0xd2, 0xd4, 0xe2, 0x12, 0x21, 0x01, 0x2e, 0xe6, 0xd2, 0xa2,
	0x1c, 0x09, 0x46, 0x05, 0x46, 0x0d, 0xce, 0x20, 0x10, 0x53, 0x48, 0x8c, 0x8b, 0x2d, 0x2d, 0x33,
	0xa7, 0x24, 0xb5, 0x48, 0x82, 0x09, 0x2c, 0x08, 0xe5, 0x29, 0xa9, 0x73, 0x71, 0xc3, 0xb4, 0x16,
	0xe4, 0x54, 0x0a, 0x49, 0x70, 0xb1, 0xe7, 0xa6, 0x16, 0x17, 0x27, 0xa6, 0xa7, 0x82, 0x35, 0x73,
	0x04, 0xc1, 0xb8, 0x46, 0xf6, 0x5c, 0xec, 0x10, 0x85, 0x45, 0x42, 0x26, 0x5c, 0x6c, 0x10, 0xa6,
	0x90, 0x08, 0xc4, 0x1d, 0x7a, 0x28, 0xb6, 0x4b, 0x09, 0xa1, 0x89, 0x16, 0xe4, 0x54, 0x2a, 0x31,
	0x38, 0x69, 0x70, 0x89, 0x27, 0xe7, 0xe7, 0xea, 0x15, 0xa7, 0x15, 0x14, 0xe5, 0xa7, 0x94, 0x26,
	0x97, 0xe4, 0x24, 0x26, 0x15, 0x43, 0x14, 0x3a, 0x41, 0x9d, 0x10, 0x00, 0xe2, 0x04, 0x30, 0x26,
	0xb1, 0x81, 0x45, 0x8d, 0x01, 0x01, 0x00, 0x00, 0xff, 0xff, 0xec, 0x57, 0x22, 0x7c, 0xec, 0x00,
	0x00, 0x00,
}
